apiVersion: apps/v1
kind: Deployment
metadata:
  name: retail-mongodb
  namespace: fss-clu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:latest
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_DATABASE
          valueFrom:
            configMapKeyRef:
              name: retail-app-config
              key: MONGO_INITDB_DATABASE

