apiVersion: v1
kind: ConfigMap
metadata:
  name: retail-app-config
  namespace: fss-clu
# ConfigMap holds non-sensitive environment variables for the retail app and MongoDB
data:
  MONGODB_URI: "mongodb://mongodb:27017/myDatabase"
  SESSION_SECRET: "1234"
  PORT: "3130"
  MONGO_INITDB_DATABASE: "myDatabase"
