name: ArgoCD Deploy

on:
  workflow_run:
    workflows: ["Build and Push Docker Image"]
    types:
      - completed

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      - name: Install ArgoCD CLI
        run: |
          curl -sSL -o argocd \
          https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
          chmod +x argocd
          sudo mv argocd /usr/local/bin/

      - name: Login ArgoCD
        run: |
          argocd login ${{ secrets.ARGOCD_SERVER }} \
          --username ${{ secrets.ARGOCD_USERNAME }} \
          --password ${{ secrets.ARGOCD_PASSWORD }} \
          --insecure

      - name: Sync Application
        run: |
          argocd app sync fss-retail-app
